name: hizb_ul_bahr
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_page_curl: ^0.1.0
  pdfrx: ^2.6.1
  # syncfusion_flutter_pdfviewer: ^27.1.55
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.4.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# --- Root-level splash configuration ---
flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: assets/splash2.png

  # Android 12 specific settings
  android_12:
    image: assets/splash2.png
    color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/book.pdf
    - assets/audio/page_turn.mp3
    - assets/audio/flip_sound.mp3